version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
    - ./zookeeper/data:/data
    ports:
    - 2182:2182

  kafka:
    image: wurstmeister/kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - ./kafka-logs:/kafka
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
